# Generated by Django 6.0.4 on 2026-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
