# Generated by Django 6.0.4 on 2026-05-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_rejection_reason_profile_verification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verification_status',
            new_name='license_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='profile',
            name='permis_recto',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='permis_verso',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
