# Generated by Django 6.0.4 on 2026-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
