# Generated by Django 6.0.4 on 2026-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_car_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contract_generated',
            field=models.BooleanField(default=False),
        ),
    ]
