# Generated by Django 6.0.4 on 2026-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='categorie',
            field=models.CharField(default='SUV', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
