# Generated by Django 6.0.4 on 2026-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_carburant_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ville',
            field=models.CharField(default='Casablanca', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='prix_par_jour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
