# Generated by Django 6.0.4 on 2026-05-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_ville_alter_car_prix_par_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.car'),
            preserve_default=False,
        ),
    ]
