# Generated by Django 6.0.4 on 2026-05-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_review_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='review',
            name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='prix_par_jour',
            field=models.FloatField(),
        ),
    ]
