# Generated by Django 6.0.4 on 2026-05-08 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_ville_remove_review_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.car'),
            preserve_default=False,
        ),
    ]
