# Generated by Django 6.0.4 on 2026-05-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_review_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ville',
            field=models.CharField(default='Casablanca', max_length=100),
        ),
    ]
