# Generated by Django 6.0.4 on 2026-05-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ville',
        ),
    ]
